version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  gateway_service:
    build: services/gateway_service
    container_name: gateway_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - library_system
      - rating_system
      - reservation_system
    volumes:
      - ./services/gateway_service:/var/www/html
    command: php -S 0.0.0.0:8080

  reservation_system:
    build: services/reservation_system
    container_name: reservation_system
    restart: always
    ports:
      - "8070:8070"
    depends_on:
      - postgres
    volumes:
      - ./services/reservation_system:/var/www/html
    command: php -S 0.0.0.0:8070

  library_system:
    build: services/library_system
    container_name: library_system
    restart: always
    ports:
      - "8060:8060"
    depends_on:
      - postgres
    volumes:
      - ./services/library_system:/var/www/html
    command: php -S 0.0.0.0:8060

  rating_system:
    build: services/rating_system
    container_name: rating_system
    restart: always
    ports:
      - "8050:8050"
    depends_on:
      - postgres
    volumes:
      - ./services/library_system:/var/www/html
    command: php -S 0.0.0.0:8050

volumes:
  db-data: